import type { CatalogSnapshot } from "../src/index.js"

export const fixtureSnapshot: CatalogSnapshot = {
  schemaVersion: 1,
  generatedAt: "2026-01-01T00:00:00.000Z",
  sources: [{ id: "fixture", name: "Fixture" }],
  generators: [],
  providers: {
    anthropic: {
      id: "anthropic",
      name: "Anthropic",
      models: {
        "claude-sonnet-4": {
          id: "claude-sonnet-4",
          name: "Claude Sonnet 4",
          family: "claude",
          attachment: true,
          reasoning: true,
          reasoning_options: [{ type: "effort", values: ["low", "medium", "high"] }],
          tool_call: true,
          structured_output: true,
          temperature: true,
          open_weights: false,
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 200_000, output: 64_000 },
        },
        "claude-legacy": {
          id: "claude-legacy",
          name: "Claude Legacy",
          family: "claude",
          attachment: false,
          reasoning: false,
          reasoning_options: [],
          tool_call: false,
          structured_output: false,
          temperature: false,
          open_weights: false,
          modalities: { input: ["text"], output: ["text"] },
          limit: { context: 8_000, output: 4_000 },
          status: "deprecated",
        },
      },
    },
    openai: {
      id: "openai",
      name: "OpenAI",
      models: {
        "gpt-4o": {
          id: "gpt-4o",
          name: "GPT-4o",
          family: "gpt-4o",
          attachment: true,
          reasoning: false,
          reasoning_options: [],
          tool_call: true,
          structured_output: true,
          temperature: true,
          open_weights: false,
          modalities: { input: ["text", "image"], output: ["text"] },
          limit: { context: 128_000, output: 16_000 },
        },
      },
    },
  },
}
