#!/usr/bin/env node
import { readFile, writeFile } from "node:fs/promises"
import { resolve } from "node:path"
import { pathToFileURL } from "node:url"
import { createCatalog } from "./catalog.js"
import { defineConfig } from "./config.js"
import { refreshSnapshot } from "./refresh.js"
import type { CatalogSnapshot, ModelCatalogConfig } from "./types.js"

const args = process.argv.slice(2)

main(args).catch((error) => {
  console.error(error instanceof Error ? error.message : String(error))
  process.exitCode = 1
})

async function main(argv: string[]) {
  const [command, ...rest] = argv

  if (!command || command === "help" || command === "--help" || command === "-h") {
    printHelp()
    return
  }

  if (command === "--version" || command === "-v") {
    console.log("0.1.0")
    return
  }

  switch (command) {
    case "refresh":
      await refreshCommand(rest)
      return
    case "generate":
      await generateCommand(rest)
      return
    case "inspect":
      await inspectCommand(rest)
      return
    case "list":
      await listCommand(rest)
      return
    default:
      throw new Error(`Unknown command '${command}'. Run 'model-catalog --help'.`)
  }
}

async function refreshCommand(argv: string[]) {
  const flags = parseFlags(argv)
  const out = getStringFlag(flags, "out")
  if (!out) throw new Error("Missing required --out path.")
  const config = await loadConfig(getStringFlag(flags, "config"))
  const snapshot = await refreshSnapshot({
    source: config.source,
    generators: config.generators,
  })
  await writeFile(resolve(out), `${JSON.stringify(snapshot, null, 2)}\n`, "utf8")
  console.log(`Wrote ${providerCount(snapshot)} providers and ${modelCount(snapshot)} models to ${out}`)
}

async function generateCommand(argv: string[]) {
  const flags = parseFlags(argv)
  const out = getStringFlag(flags, "out")
  if (!out) throw new Error("Missing required --out path.")
  const config = await loadConfig(getStringFlag(flags, "config"))
  const snapshot = await refreshSnapshot({
    source: config.source,
    generators: config.generators,
  })
  const moduleSource = [
    "/* eslint-disable */",
    "// Generated by model-catalog. Do not edit by hand.",
    'import { createCatalog } from "model-catalog";',
    "",
    `export const snapshot = ${JSON.stringify(snapshot, null, 2)};`,
    "export const catalog = createCatalog(snapshot);",
    "export default catalog;",
    "",
  ].join("\n")
  await writeFile(resolve(out), moduleSource, "utf8")
  console.log(`Generated ${out}`)
}

async function inspectCommand(argv: string[]) {
  const flags = parseFlags(argv)
  const file = flags.positionals[0]
  if (!file) throw new Error("Missing snapshot path.")
  const snapshot = await readSnapshot(file)
  const catalog = createCatalog(snapshot)
  console.log(`Providers: ${providerCount(snapshot)}`)
  console.log(`Models: ${modelCount(snapshot)}`)
  console.log(`Generated: ${snapshot.generatedAt}`)
  console.log(`Schema: ${snapshot.schemaVersion}`)
  if (snapshot.sources.length > 0) {
    console.log("Sources:")
    for (const source of snapshot.sources) console.log(`  - ${source.name ?? source.id}${source.url ? ` (${source.url})` : ""}`)
  }
  if (snapshot.generators.length > 0) {
    console.log("Generators:")
    for (const generator of snapshot.generators) console.log(`  - ${generator.name ?? generator.id}`)
  }
}

async function listCommand(argv: string[]) {
  const flags = parseFlags(argv)
  const file = flags.positionals[0]
  if (!file) throw new Error("Missing snapshot path.")
  const snapshot = await readSnapshot(file)
  const catalog = createCatalog(snapshot)
  const providerFlags = flags.provider ?? []
  const providers = providerFlags.length > 0 ? providerFlags : undefined
  const require = [...(hasFlag(flags, "reasoning") ? ["reasoning" as const] : []), ...(hasFlag(flags, "tools") || hasFlag(flags, "tool-call") ? ["tool_call" as const] : [])]
  const models = catalog.listModels({
    includeProviders: providers,
    query: getStringFlag(flags, "query") ?? getStringFlag(flags, "q"),
    require,
    minContext: getNumberFlag(flags, "min-context"),
    excludeDeprecated: hasFlag(flags, "exclude-deprecated") || undefined,
  })

  if (hasFlag(flags, "json")) {
    console.log(JSON.stringify(models, null, 2))
    return
  }

  for (const model of models) {
    const caps = model.capabilities.length > 0 ? ` [${model.capabilities.join(",")}]` : ""
    const context = model.context ? ` ctx=${model.context}` : ""
    console.log(`${model.providerId}/${model.modelId}\t${model.providerName}\t${model.name}${context}${caps}`)
  }
}

async function readSnapshot(path: string): Promise<CatalogSnapshot> {
  return JSON.parse(await readFile(resolve(path), "utf8")) as CatalogSnapshot
}

async function loadConfig(path: string | undefined): Promise<ModelCatalogConfig> {
  if (!path) return defineConfig({})
  const mod = (await import(pathToFileURL(resolve(path)).href)) as { default?: ModelCatalogConfig } & ModelCatalogConfig
  return mod.default ?? mod
}

type ParsedFlags = Record<string, string[]> & { positionals: string[] }

function parseFlags(argv: string[]): ParsedFlags {
  const flags: ParsedFlags = { positionals: [] }
  for (let index = 0; index < argv.length; index++) {
    const arg = argv[index]
    if (!arg) continue
    if (!arg.startsWith("--")) {
      flags.positionals.push(arg)
      continue
    }
    const withoutPrefix = arg.slice(2)
    const [rawKey, inlineValue] = withoutPrefix.split("=", 2)
    const key = rawKey ?? ""
    if (!key) continue
    const next = argv[index + 1]
    const value = inlineValue ?? (next && !next.startsWith("--") ? argv[++index] : "true")
    ;(flags[key] ??= []).push(value ?? "true")
  }
  return flags
}

function getStringFlag(flags: ParsedFlags, name: string): string | undefined {
  return flags[name]?.at(-1)
}

function getNumberFlag(flags: ParsedFlags, name: string): number | undefined {
  const value = getStringFlag(flags, name)
  if (value === undefined) return undefined
  const number = Number(value)
  if (!Number.isFinite(number)) throw new Error(`Expected --${name} to be a number.`)
  return number
}

function hasFlag(flags: ParsedFlags, name: string): boolean {
  return flags[name]?.some((value) => value === "true") ?? false
}

function providerCount(snapshot: CatalogSnapshot): number {
  return Object.keys(snapshot.providers).length
}

function modelCount(snapshot: CatalogSnapshot): number {
  return Object.values(snapshot.providers).reduce((count, provider) => count + Object.keys(provider.models).length, 0)
}

function printHelp() {
  console.log(`model-catalog

Usage:
  model-catalog refresh --out ./model-catalog.json [--config ./model-catalog.config.mjs]
  model-catalog generate --out ./src/model-catalog.generated.ts [--config ./model-catalog.config.mjs]
  model-catalog inspect ./model-catalog.json
  model-catalog list ./model-catalog.json [--provider anthropic] [--query claude] [--reasoning] [--tools]

Commands:
  refresh   Fetch models.dev, run generators, and write a JSON snapshot.
  generate  Fetch and write a TypeScript module exporting snapshot and catalog.
  inspect   Print snapshot summary information.
  list      Print models from a snapshot.
`)
}
